quarkus.http.port=8081
quarkus.http.test-port=0
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.swagger-ui.always-include=true

quarkus.datasource.db-kind=db2
quarkus.datasource.username=${DB2_USERNAME}
quarkus.datasource.password=${DB2_PASSWORD}
quarkus.datasource.jdbc.url=${DB2_JDBC_URL}
quarkus.hibernate-orm.schema-management.strategy=update

%dev.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
%dev.mp.messaging.outgoing.order-events.connector=smallrye-kafka
%dev.mp.messaging.outgoing.order-events.topic=order-events
%dev.mp.messaging.outgoing.order-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
%dev.mp.messaging.incoming.order-events-in.connector=smallrye-kafka
%dev.mp.messaging.incoming.order-events-in.topic=order-events
%dev.mp.messaging.incoming.order-events-in.group.id=delivery-backend
%dev.mp.messaging.incoming.order-events-in.auto.offset.reset=earliest
%dev.mp.messaging.incoming.order-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
%prod.mp.messaging.outgoing.order-events.connector=smallrye-kafka
%prod.mp.messaging.outgoing.order-events.topic=order-events
%prod.mp.messaging.outgoing.order-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
%prod.mp.messaging.incoming.order-events-in.connector=smallrye-kafka
%prod.mp.messaging.incoming.order-events-in.topic=order-events
%prod.mp.messaging.incoming.order-events-in.group.id=delivery-backend
%prod.mp.messaging.incoming.order-events-in.auto.offset.reset=earliest
%prod.mp.messaging.incoming.order-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:delivery;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.kafka.devservices.enabled=false
