quarkus.http.port=8081
quarkus.http.test-port=0
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200,http://127.0.0.1:4201
quarkus.swagger-ui.always-include=true

quarkus.datasource.db-kind=db2
quarkus.datasource.username=${DB2_USERNAME}
quarkus.datasource.password=${DB2_PASSWORD}
quarkus.datasource.jdbc.url=${DB2_JDBC_URL}
quarkus.hibernate-orm.schema-management.strategy=update

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:delivery;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-creat